---
name: PR
on:
  - pull_request
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57
        with:
          go-version: '^1.17'
      - name: go tests
        run: |
          go test -v -count=1 -race -timeout 30m ./...
      - name: integration tests
        run: |
          ./testing/integrate.sh
